### ISSUE TITLE
[BUG] Espacio en el contenedor y barra de slides. Sección Comunidad

### ISSUE THREAD

**Issue by thegreatyamori** [javascriptecuador/web#83]
**Describe el bug/error**  
Se debe mejorar la presentación del slider de Comunidad. Actualmente por diferencia de tamaños en las imágenes del slider, no se está visualizando correctamente el componente. Pero se debe añadir una pequeña separación entre el contenedor de imágenes y la barra de slides.

**Para reproducirlo** 
Pasos para reproducir el comportamiento:
1. Ir a 'localhost:8000 || javascript.ec'
2. Scroll down a 'Comunidad'
4. Ver el error

**Comportamiento esperado**  
De acuerdo con el prototipo en Figma, existe un pequeño espacio entre el contenedor de slides y la barra de slides.
![image](https://user-images.githubusercontent.com/20387293/111239384-0db6c500-85c7-11eb-9f18-b0e1797c73b7.png)

**Capturas de Pantalla**  
Este es el comportamiento actual del slider.
![image](https://user-images.githubusercontent.com/20387293/111240121-95e99a00-85c8-11eb-948b-a6181b0ecb50.png)

**Desktop:**  
 - OS: Windows 10 x64 v.20H2
 - Navegador [ Brave Browser v.1.21.76, MS Edge v.89.0.774.54 ]

**Información adicional**  
Para resolver este bug, debes arreglar este estilo en `src\components\community-section\photo-slider\photo-slider.css`
```css
.slick-dots li {
  border-radius: 10em;
  width: 11.36%;
  height: 15.65px; /* esta regla presenta conflictos. */
  margin: 0 0.4em;
}
```
